extends: airbnb
installedESLint: true
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import

env:
  browser: true
  node: true

rules:
  react/jsx-filename-extension: off

  no-underscore-dangle:
    - error
    - allow:
      - __tableName
